### ISSUE TITLE
Consider adding a marker for sentences to review later

### ISSUE THREAD

**Issue by paulmcnamee** [iscoe/dragonfly#24] opened 2018-12-13 21:29 UTC
It might be nice if sentences could be marked because they are interesting or for subsequent review.  For example, by clicking the sentence ID (a time or two).  These sentences might be written out with a mark that facilitates subsequent review.

**Comment by cash** [comment] 2019-06-15 02:23
closing as duplicate of #21

**Closed as completed by cash** 2019-06-15 02:23 UTC
